# Generated by Django 5.2.6 on 2025-09-23 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notice_event_resource_resources_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='date_added',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='user',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='resources',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('link', 'External Link')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
